import { HiraganaWord } from '../models/hiragana-word.type';

export const hiraganaWords: HiraganaWord[] = [
  { hiragana: 'あお', romaji: 'ao', englishTranslation: 'blue', dividedRomaji: 'a-o' },
  { hiragana: 'いぬ', romaji: 'inu', englishTranslation: 'dog', dividedRomaji: 'i-nu' },
  // { hiragana: 'うさぎ', romaji: 'usagi', englishTranslation: 'rabbit', dividedRomaji: 'u-sa-gi' },
  // { hiragana: 'えんぴつ', romaji: 'enpitsu', englishTranslation: 'pencil', dividedRomaji: 'e-n-pi-tsu' },
  { hiragana: 'おか', romaji: 'oka', englishTranslation: 'hill', dividedRomaji: 'o-ka' },
  { hiragana: 'かき', romaji: 'kaki', englishTranslation: 'persimmon', dividedRomaji: 'ka-ki' },
  { hiragana: 'きり', romaji: 'kiri', englishTranslation: 'mist', dividedRomaji: 'ki-ri' },
  // { hiragana: 'くじ', romaji: 'kuji', englishTranslation: 'lottery', dividedRomaji: 'ku-ji' },
  { hiragana: 'けいたい', romaji: 'keitai', englishTranslation: 'cell phone', dividedRomaji: 'ke-i-ta-i' },
  { hiragana: 'ここ', romaji: 'koko', englishTranslation: 'here', dividedRomaji: 'ko-ko' },
  { hiragana: 'さくら', romaji: 'sakura', englishTranslation: 'cherry blossom', dividedRomaji: 'sa-ku-ra' },
  { hiragana: 'しろ', romaji: 'shiro', englishTranslation: 'castle', dividedRomaji: 'shi-ro' },
  { hiragana: 'すし', romaji: 'sushi', englishTranslation: 'sushi', dividedRomaji: 'su-shi' },
  // { hiragana: 'せんぱい', romaji: 'senpai', englishTranslation: 'senior', dividedRomaji: 'se-n-pa-i' },
  // { hiragana: 'そうじ', romaji: 'souji', englishTranslation: 'cleaning', dividedRomaji: 'so-u-ji' },
  { hiragana: 'たたみ', romaji: 'tatami', englishTranslation: 'tatami mat', dividedRomaji: 'ta-ta-mi' },
  // { hiragana: 'ちょうし', romaji: 'choushi', englishTranslation: 'condition', dividedRomaji: 'cho-u-shi' },
  { hiragana: 'つくえ', romaji: 'tsukue', englishTranslation: 'desk', dividedRomaji: 'tsu-ku-e' },
  { hiragana: 'てんき', romaji: 'tenki', englishTranslation: 'weather', dividedRomaji: 'te-n-ki' },
  { hiragana: 'とけい', romaji: 'tokei', englishTranslation: 'clock', dividedRomaji: 'to-ke-i' },
  { hiragana: 'なめこ', romaji: 'nameko', englishTranslation: 'nameko mushroom', dividedRomaji: 'na-me-ko' },
  { hiragana: 'にく', romaji: 'niku', englishTranslation: 'meat', dividedRomaji: 'ni-ku' },
  // { hiragana: 'ぬいぐるみ', romaji: 'nuigurumi', englishTranslation: 'stuffed toy', dividedRomaji: 'nu-i-gu-ru-mi' },
  { hiragana: 'ねこ', romaji: 'neko', englishTranslation: 'cat', dividedRomaji: 'ne-ko' },
  { hiragana: 'のり', romaji: 'nori', englishTranslation: 'seaweed', dividedRomaji: 'no-ri' },
  { hiragana: 'はな', romaji: 'hana', englishTranslation: 'flower', dividedRomaji: 'ha-na' },
  { hiragana: 'ひと', romaji: 'hito', englishTranslation: 'person', dividedRomaji: 'hi-to' },
  { hiragana: 'ふうせん', romaji: 'fuusen', englishTranslation: 'balloon', dividedRomaji: 'fu-u-se-n' },
  { hiragana: 'へん', romaji: 'hen', englishTranslation: 'strange', dividedRomaji: 'he-n' },
  { hiragana: 'ほん', romaji: 'hon', englishTranslation: 'book', dividedRomaji: 'ho-n' },
  { hiragana: 'まち', romaji: 'machi', englishTranslation: 'town', dividedRomaji: 'ma-chi' },
  // { hiragana: 'みず', romaji: 'mizu', englishTranslation: 'water', dividedRomaji: 'mi-zu' },
  { hiragana: 'むし', romaji: 'mushi', englishTranslation: 'insect', dividedRomaji: 'mu-shi' },
  // { hiragana: 'めがね', romaji: 'megane', englishTranslation: 'glasses', dividedRomaji: 'me-ga-ne' },
  { hiragana: 'もち', romaji: 'mochi', englishTranslation: 'rice cake', dividedRomaji: 'mo-chi' },
  { hiragana: 'やきゅう', romaji: 'yakyuu', englishTranslation: 'baseball', dividedRomaji: 'ya-kyu-u' },
  // { hiragana: 'ゆうじん', romaji: 'yuujin', englishTranslation: 'friend', dividedRomaji: 'yu-u-ji-n' },
  { hiragana: 'よる', romaji: 'yoru', englishTranslation: 'night', dividedRomaji: 'yo-ru' },
  { hiragana: 'らいおん', romaji: 'raion', englishTranslation: 'lion', dividedRomaji: 'ra-i-o-n' },
  // { hiragana: 'りんご', romaji: 'ringo', englishTranslation: 'apple', dividedRomaji: 'ri-n-go' },
  { hiragana: 'るす', romaji: 'rusu', englishTranslation: 'absent', dividedRomaji: 'ru-su' },
  // { hiragana: 'れいぞうこ', romaji: 'reizouko', englishTranslation: 'refrigerator', dividedRomaji: 're-i-zo-u-ko' },
  { hiragana: 'ろうか', romaji: 'rouka', englishTranslation: 'corridor', dividedRomaji: 'ro-u-ka' },
  { hiragana: 'わに', romaji: 'wani', englishTranslation: 'crocodile', dividedRomaji: 'wa-ni' },
  // { hiragana: 'がくせい', romaji: 'gakusei', englishTranslation: 'student', dividedRomaji: 'ga-ku-se-i' },
  // { hiragana: 'ぎんこう', romaji: 'ginkou', englishTranslation: 'bank', dividedRomaji: 'gi-n-ko-u' },
  // { hiragana: 'ぐうたら', romaji: 'guutara', englishTranslation: 'lazy', dividedRomaji: 'gu-u-ta-ra' },
  // { hiragana: 'げんき', romaji: 'genki', englishTranslation: 'healthy', dividedRomaji: 'ge-n-ki' },
  // { hiragana: 'ごはん', romaji: 'gohan', englishTranslation: 'cooked rice', dividedRomaji: 'go-ha-n' },
  // { hiragana: 'ざっし', romaji: 'zasshi', englishTranslation: 'magazine', dividedRomaji: 'za-s-shi' },
  // { hiragana: 'じかん', romaji: 'jikan', englishTranslation: 'time', dividedRomaji: 'ji-ka-n' },
  // { hiragana: 'ずっと', romaji: 'zutto', englishTranslation: 'always', dividedRomaji: 'zu-tto' },
  // { hiragana: 'ぜんぶ', romaji: 'zenbu', englishTranslation: 'all', dividedRomaji: 'ze-n-bu' },
  // { hiragana: 'ぞう', romaji: 'zou', englishTranslation: 'elephant', dividedRomaji: 'zo-u' },
  // { hiragana: 'だれ', romaji: 'dare', englishTranslation: 'who', dividedRomaji: 'da-re' },
  // { hiragana: 'ぢかん', romaji: 'jikan', englishTranslation: 'time', dividedRomaji: 'ji-ka-n' },
  // { hiragana: 'づくえ', romaji: 'zukue', englishTranslation: 'desk', dividedRomaji: 'zu-ku-e' },
  // { hiragana: 'でんき', romaji: 'denki', englishTranslation: 'electricity', dividedRomaji: 'de-n-ki' },
  // { hiragana: 'どくしん', romaji: 'dokushin', englishTranslation: 'single', dividedRomaji: 'do-ku-shi-n' },
  // { hiragana: 'なぞ', romaji: 'nazo', englishTranslation: 'mystery', dividedRomaji: 'na-zo' },
  // { hiragana: 'にんじん', romaji: 'ninjin', englishTranslation: 'carrot', dividedRomaji: 'ni-n-ji-n' },
  { hiragana: 'ぬける', romaji: 'nukeru', englishTranslation: 'to come out', dividedRomaji: 'nu-ke-ru' },
  // { hiragana: 'ねずみ', romaji: 'nezumi', englishTranslation: 'mouse', dividedRomaji: 'ne-zu-mi' },
  { hiragana: 'のりもの', romaji: 'norimono', englishTranslation: 'vehicle', dividedRomaji: 'no-ri-mo-no' },
  { hiragana: 'はなみ', romaji: 'hanami', englishTranslation: 'flower viewing', dividedRomaji: 'ha-na-mi' },
  { hiragana: 'ひこうき', romaji: 'hikouki', englishTranslation: 'airplane', dividedRomaji: 'hi-ko-u-ki' },
  { hiragana: 'ふくろ', romaji: 'fukuro', englishTranslation: 'bag', dividedRomaji: 'fu-ku-ro' },
  { hiragana: 'へいわ', romaji: 'heiwa', englishTranslation: 'peace', dividedRomaji: 'he-i-wa' },
  { hiragana: 'ほし', romaji: 'hoshi', englishTranslation: 'star', dividedRomaji: 'ho-shi' },
  { hiragana: 'まと', romaji: 'mato', englishTranslation: 'target', dividedRomaji: 'ma-to' },
  { hiragana: 'みみ', romaji: 'mimi', englishTranslation: 'ear', dividedRomaji: 'mi-mi' },
  { hiragana: 'むらさき', romaji: 'murasaki', englishTranslation: 'purple', dividedRomaji: 'mu-ra-sa-ki' },
  { hiragana: 'めいし', romaji: 'meishi', englishTranslation: 'business card', dividedRomaji: 'me-i-shi' },
  // { hiragana: 'もぐら', romaji: 'mogura', englishTranslation: 'mole', dividedRomaji: 'mo-gu-ra' },
  { hiragana: 'やさい', romaji: 'yasai', englishTranslation: 'vegetable', dividedRomaji: 'ya-sa-i' },
  { hiragana: 'ゆめ', romaji: 'yume', englishTranslation: 'dream', dividedRomaji: 'yu-me' },
  { hiragana: 'ようちえん', romaji: 'youchien', englishTranslation: 'kindergarten', dividedRomaji: 'yo-u-chi-e-n' },
  // { hiragana: 'らっぱ', romaji: 'rappa', englishTranslation: 'trumpet', dividedRomaji: 'ra-ppa' },
  // { hiragana: 'りんじん', romaji: 'rinjin', englishTranslation: 'neighbor', dividedRomaji: 'ri-n-ji-n' },
];
